<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    integer         irn
    text short      AdmPublishWebNoPassword
    text short      TitAccessionNo
    text short      TitPreviousAccessionNo
    text short      TitObjectStatus
    date            TitAccessionDate
    text long       TitMainTitle
    text long       TitSeriesTitle
    text long       TitCollectionTitle
    table           AltTitles
      text long       TitAlternateTitles
    end
    text long       TitTitleNotes
    text short      TitObjectType
    table           ObjectTypes
      text short      PhyMediaCategory
    end
    text short      CreDateCreated
    date            CreEarliestDate
    date            CreLatestDate
    text short      CreCreationPeriod
    text long       CreCreationDynasty
    table           Creator1
      text short      CreRole
      text long       CreCreatorAfterFollower
      integer         irn
      text long       SummaryData
    end
    table           Creator2
      text long       CreCreatorAttribution
      text long       CreCreationCultureOrPeople
      text long       CreCreationNationality2
    end
    table           CreLocation
      text short      CreCountry
      text short      CreState
      text short      CreDistrict
      text short      CreCity
    end
    table           MarkType
      text short      CreMarkType
    end
    text long       CrePrimaryInscriptions
    text long       CreCreationNotes
    date            EdiPublisherDate
    table           Medium
      text long       PhyMedium
    end
    table           Support
      text short      PhySupport
    end
    text long       PhyMediumAndSupport
    text short      PhyStyle
    text short      PhyTechnique
    text short      EdiImpression
    text long       PhyDescription
    table           Color
      text short      PhyColor
    end
    text long       PhyConvertedDims
    table           Dimensions
      text short      PhyType
      float           PhyHeight
      float           PhyWidth
      float           PhyDepth
      float           PhyDiameter
      text short      PhyUnitLength
      float           PhyWeight
      text short      PhyUnitWeight
      text short      PhyDimensionNotes
    end
    text long       SumCreditLine
    table           Rights
      text long       RigAcknowledgement
    end
    text long       CreProvenance
    text short      PhyCollectionArea
    text short      LocMovementType
    tuple           LocCurrentLocationRef
      text short      LocLevel1
      text short      LocLevel2
      text short      LocLevel3
    end
    tuple           AssParentObjectRef
      integer         irn
    end
    text short      AssIsParent
    table           Children
      integer         irn
      text long       TitMainTitle
      table           Grandchildren
        integer         irn
        text long       TitMainTitle
      end
    end
    table           Related
      text short      AssRelationship
      integer         irn
    end
    text short      AdmPublishWebNoPassword
    table           Homepage
      text short      RefBibliographicNotes
      integer         irn
      text long       EleTitle
      text short      EleIdentifier
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 1 -->
  <tuple>
    <atom name="irn">3811</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">01.4</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">1901-04-09</atom>
    <atom name="TitMainTitle">Marine</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Visual Works: Paintings</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">paintings</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">oil paintings</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">before 1902</atom>
    <atom name="CreEarliestDate">1865</atom>
    <atom name="CreLatestDate">1901</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Artist</atom>
        <atom name="irn">628098</atom>
        <atom name="SummaryData">Wendt, William</atom>
      </tuple>
    </table>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">United States</atom>
      </tuple>
    </table>
    <table name="MarkType">
      <tuple>
        <atom name="CreMarkType">Signature</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions">Signed, lower left: WM. WENDT</atom>
    <atom name="CreCreationNotes">Based on IMA accession date.</atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">oil paint</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">canvas</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">oil on canvas</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique">painting</atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">24-1/4 x 36-1/4 in. (canvas)
35-3/4 x 47-1/2 x 2-3/4 in. (framed)</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">IMA Number Applied</atom>
        <atom name="PhyHeight"></atom>
        <atom name="PhyWidth"></atom>
        <atom name="PhyDepth"></atom>
        <atom name="PhyUnitLength"></atom>
        <atom name="PhyDimensionNotes">in red ink to backing in upper left corner and to frame in upper and lower left corners</atom>
      </tuple>
      <tuple>
        <atom name="PhyType">Framed Dimensions</atom>
        <atom name="PhyHeight">35.7500</atom>
        <atom name="PhyWidth">47.5000</atom>
        <atom name="PhyDepth">2.7500</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 90.8 x 120.6 x 7 (framed)</atom>
      </tuple>
      <tuple>
        <atom name="PhyType">Unframed Dimensions</atom>
        <atom name="PhyHeight">24.2500</atom>
        <atom name="PhyWidth">36.2500</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 61.6 x 92 (canvas)</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">John Herron Fund</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">Â© William Wendt</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">901.2-American Painting and Sculpture 1800-1945</atom>
    <atom name="LocMovementType">Storage Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">storage</atom>
      <atom name="LocLevel3">P</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">56210</atom>
        <atom name="irn">6037</atom>
        <atom name="EleTitle">Dagwood ID for 01.4</atom>
        <atom name="EleIdentifier">56210</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="irn">4229</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">33.271</atom>
    <atom name="TitPreviousAccessionNo"></atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">1933-11-21</atom>
    <atom name="TitMainTitle">pillow cover</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Costume</atom>
    <atom name="CreDateCreated">late 19th century</atom>
    <atom name="CreEarliestDate"></atom>
    <atom name="CreLatestDate"></atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">Morocco</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <atom name="PhyMediumAndSupport">Silk On Cotton</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique"></atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">50 x 21 in.</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Warp</atom>
        <atom name="PhyHeight">50.5000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 128.2699981 cm warp --- Dimension Notes: w/o</atom>
      </tuple>
      <tuple>
        <atom name="PhyType">Weft</atom>
        <atom name="PhyHeight">24.2500</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 61.59499907 cm weft --- Dimension Notes: w/o</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">The Eliza M. and Sarah L. Niblack Collection</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">No Known Rights Holder</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">908-Textile and Fashion Arts</atom>
    <atom name="LocMovementType">Inventory 2014-2015</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">storage</atom>
      <atom name="LocLevel3">Tc16</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">54094</atom>
        <atom name="irn">6451</atom>
        <atom name="EleTitle">Dagwood ID for 33.271</atom>
        <atom name="EleIdentifier">54094</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="irn">4549</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">13.308</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">1913-06-30</atom>
    <atom name="TitMainTitle">Roscoe's Yellow Throat</atom>
    <atom name="TitSeriesTitle">Birds of America</atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Visual Works: Prints</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">prints</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">etchings</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1827-1838</atom>
    <atom name="CreEarliestDate">1827</atom>
    <atom name="CreLatestDate">1838</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Artist</atom>
        <atom name="irn">614740</atom>
        <atom name="SummaryData">Havell, Robert</atom>
      </tuple>
      <tuple>
        <atom name="CreRole">Artist</atom>
        <atom name="irn">616206</atom>
        <atom name="SummaryData">Audubon, John James</atom>
      </tuple>
    </table>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">United States | England</atom>
      </tuple>
    </table>
    <table name="MarkType">
      <tuple>
        <atom name="CreMarkType">Watermark</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions">J WHATMAN</atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">ink</atom>
      </tuple>
      <tuple>
        <atom name="PhyMedium">pigment</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">paper</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">ink on paper, hand-colored etching</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique">etching</atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">19-1/4 x 12-1/8 in. (plate)
27-1/8 x 21-1/2 in. (sheet)</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Plate Dimensions</atom>
        <atom name="PhyHeight">19.2500</atom>
        <atom name="PhyWidth">12.1250</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 48.9 x 30.8 (plate)</atom>
      </tuple>
      <tuple>
        <atom name="PhyType">Sheet Dimensions</atom>
        <atom name="PhyHeight">27.1250</atom>
        <atom name="PhyWidth">21.5000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 68.9 x 54.6 (sheet)</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">John Herron Fund</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">904.1-Prints, Drawings, and Photographs</atom>
    <atom name="LocMovementType">Storage Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">Print Storage</atom>
      <atom name="LocLevel3">F25</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <table name="Related">
      <tuple>
        <atom name="AssRelationship">associated</atom>
        <atom name="irn">4550</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">associated</atom>
        <atom name="irn">4551</atom>
      </tuple>
    </table>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">57881</atom>
        <atom name="irn">6771</atom>
        <atom name="EleTitle">Dagwood ID for 13.308</atom>
        <atom name="EleIdentifier">57881</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="irn">6347</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">77.319</atom>
    <atom name="TitPreviousAccessionNo"></atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate"></atom>
    <atom name="TitMainTitle">Buddha</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Visual Works: Sculpture</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">sculptures</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">figures</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1500s</atom>
    <atom name="CreEarliestDate">1500</atom>
    <atom name="CreLatestDate">1599</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty">Ming dynasty</atom>
    <table name="Creator2">
      <tuple>
        <atom name="CreCreationNationality2">Chinese</atom>
      </tuple>
    </table>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">China</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">cast iron</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">cast iron</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique"></atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription">very large head of the Buddha in cast iron, with downcast eyes and meditative expression.  The hair is upswept in neat ridges and tied at the top of the head.  The cranial protuberance and extended earlobes are physical attributes that are typical of representations of the Buddha.  The surface of the head show seams of the mold in which it was originally cast.</atom>
    <atom name="PhyConvertedDims">43 x 26 in.</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">43.0000</atom>
        <atom name="PhyWidth">26.0000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyWeight"></atom>
        <atom name="PhyUnitWeight"></atom>
        <atom name="PhyDimensionNotes">Metric: 109.2 x 66.0</atom>
      </tuple>
      <tuple>
        <atom name="PhyType">Weight</atom>
        <atom name="PhyWeight">8800.0000</atom>
        <atom name="PhyUnitWeight">oz.</atom>
        <atom name="PhyDimensionNotes">estimated weight of 550 lbs. weight with base is 582 lbs. (10/27/03)</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Gift of Mr. and Mrs. Charles B. Miller in memory of Donald G. Martinelli</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <atom name="CreProvenance">Mr. and Mrs. Charles B. Miller; given to the Indianapolis Museum of Art in 1977.</atom>
    <atom name="PhyCollectionArea">905.1-Asian Art (Chinese and other Asian)</atom>
    <atom name="LocMovementType">Inventory 2014-2015</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">F5</atom>
      <atom name="LocLevel3"></atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">31882</atom>
        <atom name="irn">8564</atom>
        <atom name="EleTitle">Dagwood ID for 77.319</atom>
        <atom name="EleIdentifier">31882</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="irn">6375</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <atom name="TitAccessionNo">TR7099</atom>
    <atom name="TitPreviousAccessionNo"></atom>
    <atom name="TitObjectStatus">Loan Permanent Collection</atom>
    <atom name="TitAccessionDate"></atom>
    <atom name="TitMainTitle">fountain</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Visual Works: Sculpture</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">fountains</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">sculptures</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">about 1860</atom>
    <atom name="CreEarliestDate">1855</atom>
    <atom name="CreLatestDate">1865</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator2">
      <tuple>
        <atom name="CreCreationNationality2">Italian</atom>
      </tuple>
    </table>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">Italy</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">bronze</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">marble</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">bronze figurine, Cipollino marble bowl and support</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique">carving</atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription">Functioning Cipollino marble fountain.  The upper bowl is carved with mermaid and dolphin motif with an octagonal pedestal base.  A finely modelled bronze standing fountain figure of "The Verrocchio Boy" holding a dolphin in his arms is situated at the top center of the upper bowl with right leg lifted to the side and bent at the knee slight to the back and the left support leg is on a domed base.  The lower bowl, pool-surround is of Sicilian marble exhibiting rounded edges.</atom>
    <atom name="PhyConvertedDims">approximately 108 x 96 x 96 in.
lower bowl: approximately 12 x 96 x 96 in.
lower bowl water volume: approximately 20.25 (circumference) x W:2.1 x H:.75 ft. = 31.89 cubic feet 
upper bowl water volume: approximately 8.5 (circumference) x W:.66 x H:.17 = .95 cubic feet</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">108.0000</atom>
        <atom name="PhyWidth">96.0000</atom>
        <atom name="PhyDepth">96.0000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">approximately</atom>
      </tuple>
      <tuple>
        <atom name="PhyType">Volume</atom>
        <atom name="PhyDimensionNotes">approximately 246 gallons of water (upper bowl 7 gallons, lower bowl 249 gallons)</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">The Clowes Fund, Inc.</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <atom name="CreProvenance">By direction of Allen Whitehill Clowes, The Clowes Fund, Inc., Indianapolis, Indiana, purchased in 1990  from T. Crowther and Son Ltd. London, England; given to the Indianapolis Museum of Art in 1990.</atom>
    <atom name="PhyCollectionArea">902.1-European Painting and Sculpture Before 1800</atom>
    <atom name="LocMovementType">Exhibition Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">Medieval Renaissance Gallery</atom>
      <atom name="LocLevel3">C202</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">No</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">34007</atom>
        <atom name="irn">8592</atom>
        <atom name="EleTitle">Dagwood ID for TR7099</atom>
        <atom name="EleIdentifier">34007</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="irn">8498</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">09.140</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitObjectStatus">Deaccessioned</atom>
    <atom name="TitAccessionDate">1909-01-25</atom>
    <atom name="TitMainTitle">Black Friar's Bridge</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Visual Works: Prints</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">prints</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">engravings</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1795</atom>
    <atom name="CreEarliestDate">1795</atom>
    <atom name="CreLatestDate">1795</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Artist</atom>
        <atom name="irn">1748</atom>
        <atom name="SummaryData">Taylor, Charles</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">ink</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">paper</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">ink on paper, engraving</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique">engraving {printing process}</atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">5 (diam.) in.
11-1/4 x 7-1/8 in. (mount)</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight"></atom>
        <atom name="PhyWidth"></atom>
        <atom name="PhyDiameter">5.0000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 12.7 (diam.)</atom>
      </tuple>
      <tuple>
        <atom name="PhyType">Mount Dimensions</atom>
        <atom name="PhyHeight">11.2500</atom>
        <atom name="PhyWidth">7.1300</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 28.57 x 18.09 (mount)</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Gift of Mrs. Anna J. Brownell and Miss Frances J. Brownell</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">904.1-Prints, Drawings, and Photographs</atom>
    <atom name="LocMovementType">Other Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">Disposed</atom>
      <atom name="LocLevel3"></atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">57196</atom>
        <atom name="irn">10705</atom>
        <atom name="EleTitle">Dagwood ID for 09.140</atom>
        <atom name="EleIdentifier">57196</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <atom name="irn">9460</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">08.46</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">1908-09-21</atom>
    <atom name="TitMainTitle">Allegorical Subject</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Visual Works: Prints</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">engravings</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">etchings</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">prints</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">17th century</atom>
    <atom name="CreEarliestDate">1601</atom>
    <atom name="CreLatestDate">1700</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Artist</atom>
        <atom name="irn">608337</atom>
        <atom name="SummaryData">Vignon, Claude</atom>
      </tuple>
      <tuple>
        <atom name="CreRole">Engraver</atom>
        <atom name="irn">630516</atom>
        <atom name="SummaryData">Bosse, Abraham</atom>
      </tuple>
    </table>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">France</atom>
      </tuple>
    </table>
    <table name="MarkType">
      <tuple>
        <atom name="CreMarkType">Signature</atom>
      </tuple>
      <tuple>
        <atom name="CreMarkType">Inscriptions</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions">Signed in plate: C. Vignonjn, A. Bosse sculp.
Inscribed, verso: Benedette Castiglion</atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">ink</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">paper</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">ink on paper, engraving and etching</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique">engraving {printing process}</atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">10-1/4 x 7-1/8 in. (image)
13 x 9-1/4 in. (mount)</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Image Dimensions</atom>
        <atom name="PhyHeight">10.2500</atom>
        <atom name="PhyWidth">7.1800</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 26.03 x 18.2 (image)</atom>
      </tuple>
      <tuple>
        <atom name="PhyType">Mount Dimensions</atom>