<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           eevents
    integer         irn
    text short      EveEventNumber
    text short      EveExhibitionStatus
    text short      EveInternalOrExternalEvent
    text long       EveEventTitle
    table           TasCommencementDate0
      date            TasCommencementDate
    end
    table           TasCompletionDate0
      date            TasCompletionDate
    end
    text long       EveEventDescription
    table           ObjEventCatalogueNumber_tab
      text short      ObjEventCatalogueNumber
    end
    table           Objects
      integer         irn
      text long       TitMainTitle
      text short      TitAccessionNo
      text short      TitObjectStatus
      text long       SumCreditLine
      table           RigRightsRef_tab
        text long       RigAcknowledgement
      end
      text short      RefCatalogueRaisonne
      text short      CreDateCreated
      text short      CreDateDesigned
      table           Creator1
        text short      CreRole
        text long       CreCreatorAfterFollower
        integer         irn
        text long       NamFullName
        text short      NamFirst
        text short      NamMiddle
        text short      NamLast
        text long       NamOrganisation
        text short      ColCollaborationName
        text short      UlaName
        text short      UlaUlanIdNo
        text short      BioNationality
      end
      table           Creator2
        text long       CreCreatorAttribution
        text long       CreCreationCultureOrPeople
        text long       CreCreationNationality2
      end
      text short      TitObjectType
      text short      AdmPublishWebNoPassword
      table           Dagwood
        text long       EleTitle
        text short      RefBibliographicNotes
      end
      text short      ObjEventSection
      text long       ObjAttachedObjectsNotes
    end
    table           Master
      tuple           EveMasterEventRef
        integer         irn
        text short      EveExhibitionStatus
        text short      EveEventNumber
        text long       EveEventTitle
        table           TasCommencementDate0
          date            TasCommencementDate
        end
        table           TasCompletionDate0
          date            TasCompletionDate
        end
        text short      AdmPublishWebNoPassword
        text short      EveInternalOrExternalEvent
      end
    end
    table           Venues
      integer         irn
      text long       NamFullName
      text long       NamOrganisation
      text long       AddWeb
      text long       AddPostStreet
      text short      AddPostCity
      text short      AddPostState
      text short      AddPostPost
      text short      AddPostCountry
      date            VenVenueCommencementDate
      date            VenVenueCompletionDate
    end
    table           Curator
      integer         irn
      text long       NamFullName
      text short      NamFirst
      text short      NamMiddle
      text short      NamLast
    end
    table           Designer
      integer         irn
      text long       NamFullName
      text short      NamFirst
      text short      NamMiddle
      table           IhhCollectionLastName_tab
        text short      IhhCollectionLastName
      end
    end
    table           Organizer
      integer         irn
      text long       NamFullName
      text short      NamFirst
      text short      NamMiddle
      text short      NamLast
      text long       NamOrganisation
      text short      ColCollaborationName
      text long       AddWeb
      text long       AddPostStreet
      text short      AddPostCity
      text short      AddPostState
      text short      AddPostPost
      text short      AddPostCountry
    end
  end
?>
<!-- Data -->
<table name="eevents">

  <!-- Row 1 -->
  <tuple>
    <atom name="irn">3547</atom>
    <atom name="EveEventNumber">EX2008.27</atom>
    <atom name="EveExhibitionStatus">Completed</atom>
    <atom name="EveInternalOrExternalEvent">Internal</atom>
    <atom name="EveEventTitle">Mark Lewis: Rear Projection: Molly Parker</atom>
    <atom name="EveEventDescription">Since the mid 1990s, London-based artist Mark Lewis has made short films that explore the concept of the moving image.  By isolating cinematic techniques such as the single tracking shot or reverse zoom, Lewis structures his films to bring attention to the technical and descriptive conventions of filmmaking. Lewis' works bring focus to seemingly secondary information-background details such as landscape, everyday architecture, and film extras-repositioning these elements so that they occupy the central role.

For his exhibition in the Carmen &amp; Mark Holeman Video Gallery, IMA presents Lewis' 2006 work Rear Projection: Molly Parker, which looks to the outmoded technique of rear projection (now replaced by blue screen technology).  Engaging a technique originally meant to communicate realism, Rear Projection: Molly Parker draws attention to its own artifice and creates a mysterious disjuncture of time and space.</atom>
    <table name="Objects">
      <tuple>
        <atom name="irn">67078</atom>
        <atom name="TitMainTitle">Rear Projection: Molly Parker</atom>
        <atom name="TitAccessionNo">TR10760</atom>
        <atom name="TitObjectStatus">Loan Exhibition</atom>
        <atom name="SumCreditLine">Couresy of the Shlesinger Family, Toronto</atom>
        <atom name="RefCatalogueRaisonne"></atom>
        <atom name="CreDateCreated">2006</atom>
        <atom name="CreDateDesigned"></atom>
        <table name="Creator1">
          <tuple>
            <atom name="CreRole">Artist</atom>
            <atom name="irn">715289</atom>
            <atom name="NamFullName">Mark Lewis</atom>
            <atom name="NamFirst">Mark</atom>
            <atom name="NamMiddle"></atom>
            <atom name="NamLast">Lewis</atom>
            <atom name="NamOrganisation"></atom>
            <atom name="ColCollaborationName"></atom>
            <atom name="UlaName">Lewis, Mark</atom>
            <atom name="UlaUlanIdNo">500121255</atom>
            <atom name="BioNationality">Canadian</atom>
          </tuple>
        </table>
        <atom name="TitObjectType">Art Object</atom>
        <atom name="AdmPublishWebNoPassword">No</atom>
        <table name="Dagwood">
          <tuple>
            <atom name="EleTitle">Dagwood ID for TR10760</atom>
            <atom name="RefBibliographicNotes">18060</atom>
          </tuple>
        </table>
        <atom name="ObjEventSection">Video Gallery</atom>
        <atom name="ObjAttachedObjectsNotes">OG8825</atom>
      </tuple>
    </table>
    <table name="Curator">
      <tuple>
        <atom name="irn">5639</atom>
        <atom name="NamFullName">Sarah Green</atom>
        <atom name="NamFirst">Sarah</atom>
        <atom name="NamMiddle"></atom>
        <atom name="NamLast">Green</atom>
      </tuple>
    </table>
    <table name="Designer">
      <tuple>
        <atom name="irn">4550</atom>
        <atom name="NamFullName">David Russick</atom>
        <atom name="NamFirst">David</atom>
        <atom name="NamMiddle"></atom>
      </tuple>
    </table>
    <table name="Organizer">
      <tuple>
        <atom name="irn">1</atom>
        <atom name="NamFullName">Indianapolis Museum of Art at Newfields</atom>
        <atom name="NamFirst"></atom>
        <atom name="NamMiddle"></atom>
        <atom name="NamLast"></atom>
        <atom name="NamOrganisation">Indianapolis Museum of Art at Newfields</atom>
        <atom name="ColCollaborationName"></atom>
        <atom name="AddWeb">https://discovernewfields.org/</atom>
        <atom name="AddPostStreet">4000 Michigan Road</atom>
        <atom name="AddPostCity">Indianapolis</atom>
        <atom name="AddPostState">Indiana</atom>
        <atom name="AddPostPost">46208-3326</atom>
        <atom name="AddPostCountry"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="irn">3989</atom>
    <atom name="EveEventNumber">EX2012.26</atom>
    <atom name="EveExhibitionStatus">Completed</atom>
    <atom name="EveInternalOrExternalEvent">Internal</atom>
    <atom name="EveEventTitle">Allora &amp; Calzadilla: The Vieques Series</atom>
    <atom name="EveEventDescription">"Allora &amp; Calzadilla: The Vieques Series" is an exhibition of short videos by the artists Jennifer Allora &amp; Guillermo Calzadilla filmed on the Puerto Rican island of Vieques. This island was controlled primarily by the U.S. Navy until 2003, when military exercises ceased and environmental remediation began. The videos, which have never before been presented together in the U.S., include "Returning a Sound" (2004), "Under Discussion" (2005) and "Half Mast\Full Mast" (2011). As the Vieques Series demonstrates, the cessation of the military from the land is a victory by the locals that has initiated a longer sequence of events. The residents of Vieques continue to debate about the best future for the recently demilitarized land and strive for a democratic process of negotiation among the islands residents rather than a future mandated by the U.S. government or wealthy investors.</atom>
    <table name="Objects">
      <tuple>
        <atom name="ObjEventSection">Carmen &amp; Mark Holeman Gallery</atom>
      </tuple>
    </table>
    <table name="Curator">
      <tuple>
        <atom name="irn">117</atom>
        <atom name="NamFullName">Dr. Lisa Freiman</atom>
        <atom name="NamFirst">Lisa</atom>
        <atom name="NamMiddle"></atom>
        <atom name="NamLast">Freiman</atom>
      </tuple>
    </table>
    <table name="Designer">
      <tuple>
        <atom name="irn">7789</atom>
        <atom name="NamFullName">Lara Huchteman</atom>
        <atom name="NamFirst">Lara</atom>
        <atom name="NamMiddle"></atom>
      </tuple>
    </table>
    <table name="Organizer">
      <tuple>
        <atom name="irn">1</atom>
        <atom name="NamFullName">Indianapolis Museum of Art at Newfields</atom>
        <atom name="NamFirst"></atom>
        <atom name="NamMiddle"></atom>
        <atom name="NamLast"></atom>
        <atom name="NamOrganisation">Indianapolis Museum of Art at Newfields</atom>
        <atom name="ColCollaborationName"></atom>
        <atom name="AddWeb">https://discovernewfields.org/</atom>
        <atom name="AddPostStreet">4000 Michigan Road</atom>
        <atom name="AddPostCity">Indianapolis</atom>
        <atom name="AddPostState">Indiana</atom>
        <atom name="AddPostPost">46208-3326</atom>
        <atom name="AddPostCountry"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="irn">3380</atom>
    <atom name="EveEventNumber">EX2012.1</atom>
    <atom name="EveExhibitionStatus">Completed</atom>
    <atom name="EveInternalOrExternalEvent">Internal</atom>
    <atom name="EveEventTitle">Snapshot: Painters and Photography, Bonnard to Vuillard</atom>
    <atom name="EveEventDescription">The invention of the handheld Kodak camera in 1888 expanded the practice of photography to the general public. Artists were not immune to its allure, and during the 1890s several Post-Impressionists made intriguing photographic experiments that recorded their daily lives and related directly to how they composed their oil paintings and works on paper. Featured artists include some of the finest interpreters of the new "snapshot" medium, such as Pierre Bonnard, Maurice Denis, Félix Vallotton, Edouard Vuillard, all members of the Nabi group, as well as Dutch artist Georg Breitner and the Belgian Henri Evenepoel. Their photographs, largely unknown, will be displayed alongside their paintings and prints, offering new insights into the works for which they are renowned.

The exhibition features approximately 200 photographs, 40 paintings and 60 works on paper, including interiors, urban scenes and portraiture. Exhibition curators are Elizabeth Easton, director of the Center for Curatorial Leadership; Eliza Rathbone, chief curator, The Phillips Collection, Washington, D.C., and Ellen Lee, Wood-Pulliam Senior Curator, Indianapolis Museum of Art. "Bonnard to Vuillard" will open at the Van Gogh Museum in Fall 2011, and then travel to the Phillips Collection for a February 2012 opening before opening at the IMA in June 2012.</atom>
    <table name="Objects">
      <tuple>
        <atom name="irn">26665</atom>
        <atom name="TitMainTitle">The Mirror in the Green Room (La Glace de la Chambre Verte)</atom>
        <atom name="TitAccessionNo">38.84</atom>
        <atom name="TitObjectStatus">Accessioned</atom>
        <atom name="SumCreditLine">James E. Roberts Fund</atom>
        <table name="RigRightsRef_tab">
          <tuple>
            <atom name="RigAcknowledgement">© Pierre Bonnard / Artists Rights Society (ARS), NY</atom>
          </tuple>
        </table>
        <atom name="RefCatalogueRaisonne"></atom>
        <atom name="CreDateCreated">1908</atom>
        <atom name="CreDateDesigned"></atom>
        <table name="Creator1">
          <tuple>
            <atom name="CreRole">Artist</atom>
            <atom name="irn">710447</atom>
            <atom name="NamFullName">Pierre Bonnard</atom>
            <atom name="NamFirst">Pierre</atom>
            <atom name="NamMiddle"></atom>
            <atom name="NamLast">Bonnard</atom>
            <atom name="NamOrganisation"></atom>
            <atom name="ColCollaborationName"></atom>
            <atom name="UlaName">Bonnard, Pierre</atom>
            <atom name="UlaUlanIdNo">500115555</atom>
            <atom name="BioNationality">French</atom>
          </tuple>
        </table>
        <atom name="TitObjectType">Visual Works: Paintings</atom>
        <atom name="AdmPublishWebNoPassword">Yes</atom>
        <table name="Dagwood">
          <tuple>
            <atom name="EleTitle"></atom>
            <atom name="RefBibliographicNotes"></atom>
          </tuple>
          <tuple>
            <atom name="EleTitle"></atom>
            <atom name="RefBibliographicNotes"></atom>
          </tuple>
          <tuple>
            <atom name="EleTitle"></atom>
            <atom name="RefBibliographicNotes"></atom>
          </tuple>
          <tuple>
            <atom name="EleTitle"></atom>
            <atom name="RefBibliographicNotes"></atom>
          </tuple>
          <tuple>
            <atom name="EleTitle"></atom>
            <atom name="RefBibliographicNotes"></atom>
          </tuple>
          <tuple>
            <atom name="EleTitle"></atom>
            <atom name="RefBibliographicNotes"></atom>
          </tuple>
          <tuple>
            <atom name="EleTitle"></atom>
            <atom name="RefBibliographicNotes"></atom>
          </tuple>
          <tuple>
            <atom name="EleTitle"></atom>
            <atom name="RefBibliographicNotes">p. 13 (reproduced in color)</atom>
          </tuple>
          <tuple>
            <atom name="EleTitle"></atom>
            <atom name="RefBibliographicNotes">p. 84 (reproduced in black and white)</atom>
          </tuple>
          <tuple>
            <atom name="EleTitle"></atom>
            <atom name="RefBibliographicNotes">p. 39, pl.17 (reproduction is in color)</atom>
          </tuple>
          <tuple>
            <atom name="EleTitle">Dagwood ID for 38.84</atom>
            <atom name="RefBibliographicNotes">52934</atom>
          </tuple>
          <tuple>
            <atom name="EleTitle"></atom>
            <atom name="RefBibliographicNotes">p. 55 (reproduced in color)</atom>
          </tuple>
        </table>
        <atom name="ObjEventSection">AWC</atom>
      </tuple>
      <tuple>
        <atom name="irn">34255</atom>
        <atom name="TitMainTitle">Rue vue d'en haut</atom>
        <atom name="TitAccessionNo">49.61</atom>
        <atom name="TitObjectStatus">Accessioned</atom>
        <atom name="SumCreditLine">Carl H. Lieber Memorial Fund</atom>
        <table name="RigRightsRef_tab">
          <tuple>
            <atom name="RigAcknowledgement">© Pierre Bonnard / Artists Rights Society (ARS), NY</atom>
          </tuple>
        </table>
        <atom name="RefCatalogueRaisonne"></atom>
        <atom name="CreDateCreated">1895</atom>
        <atom name="CreDateDesigned"></atom>
        <table name="Creator1">
          <tuple>
            <atom name="CreRole">Artist</atom>
            <atom name="irn">710447</atom>
            <atom name="NamFullName">Pierre Bonnard</atom>
            <atom name="NamFirst">Pierre</atom>
            <atom name="NamMiddle"></atom>
            <atom name="NamLast">Bonnard</atom>
            <atom name="NamOrganisation"></atom>
            <atom name="ColCollaborationName"></atom>
            <atom name="UlaName">Bonnard, Pierre</atom>
            <atom name="UlaUlanIdNo">500115555</atom>
            <atom name="BioNationality">French</atom>
          </tuple>
          <tuple>
            <atom name="CreRole">Printer</atom>
            <atom name="irn">2093</atom>
            <atom name="NamFullName">Auguste Clot</atom>
            <atom name="NamFirst">Auguste</atom>
            <atom name="NamMiddle"></atom>
            <atom name="NamLast">Clot</atom>
            <atom name="NamOrganisation"></atom>
            <atom name="ColCollaborationName"></atom>
            <atom name="UlaName">Clot, Auguste</atom>
            <atom name="UlaUlanIdNo">500058534</atom>
            <atom name="BioNationality">French</atom>
          </tuple>
        </table>
        <atom name="TitObjectType">Visual Works: Prints</atom>
        <atom name="AdmPublishWebNoPassword">Yes</atom>
        <table name="Dagwood">
          <tuple>
            <atom name="EleTitle">Dagwood ID for 49.61</atom>
            <atom name="RefBibliographicNotes">69214</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <atom name="irn">77253</atom>
        <atom name="TitMainTitle">Gabrielle Vallotton in a nightgown standing before an open cupboard</atom>
        <atom name="TitAccessionNo">TR11390/6</atom>
        <atom name="TitObjectStatus">Returned</atom>
        <atom name="SumCreditLine"></atom>
        <table name="RigRightsRef_tab">
          <tuple>
            <atom name="RigAcknowledgement">Public Domain</atom>
          </tuple>
        </table>
        <atom name="RefCatalogueRaisonne"></atom>
        <atom name="CreDateCreated"></atom>
        <atom name="CreDateDesigned"></atom>
        <table name="Creator1">
          <tuple>
            <atom name="CreRole">Artist</atom>
            <atom name="irn">616677</atom>
            <atom name="NamFullName">Félix E. Vallotton</atom>
            <atom name="NamFirst">Félix</atom>
            <atom name="NamMiddle">Edouard</atom>
            <atom name="NamLast">Vallotton</atom>
            <atom name="NamOrganisation"></atom>
            <atom name="ColCollaborationName"></atom>
            <atom name="UlaName">Vallotton, Félix Edouard</atom>
            <atom name="UlaUlanIdNo">500017056</atom>
            <atom name="BioNationality">Swiss</atom>
          </tuple>
        </table>
        <atom name="TitObjectType">Visual Works: Photographs</atom>
        <atom name="AdmPublishWebNoPassword">No</atom>
        <table name="Dagwood">
          <tuple>
            <atom name="EleTitle">Dagwood ID for TR11390/6</atom>
            <atom name="RefBibliographicNotes">47696</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <atom name="irn">72563</atom>
        <atom name="TitMainTitle">At Table, Lunch</atom>
        <atom name="TitAccessionNo">TR11285/1</atom>
        <atom name="TitObjectStatus">Returned</atom>
        <atom name="SumCreditLine"></atom>
        <table name="RigRightsRef_tab">
          <tuple>
            <atom name="RigAcknowledgement">Public Domain</atom>
          </tuple>
        </table>
        <atom name="RefCatalogueRaisonne"></atom>
        <atom name="CreDateCreated">1892</atom>
        <atom name="CreDateDesigned"></atom>
        <table name="Creator1">
          <tuple>
            <atom name="CreRole">Artist</atom>
            <atom name="irn">614616</atom>
            <atom name="NamFullName">Edouard Vuillard</atom>
            <atom name="NamFirst">Edouard</atom>
            <atom name="NamMiddle"></atom>
            <atom name="NamLast">Vuillard</atom>
            <atom name="NamOrganisation"></atom>
            <atom name="ColCollaborationName"></atom>
            <atom name="UlaName">Vuillard, Edouard</atom>
            <atom name="UlaUlanIdNo">500014954</atom>
            <atom name="BioNationality">French</atom>
          </tuple>
        </table>
        <atom name="TitObjectType">Visual Works: Paintings</atom>
        <atom name="AdmPublishWebNoPassword">No</atom>
        <table name="Dagwood">
          <tuple>
            <atom name="EleTitle">Dagwood ID for TR11285/1</atom>
            <atom name="RefBibliographicNotes">30069</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <atom name="irn">72564</atom>
        <atom name="TitMainTitle">The Lady at the Window</atom>
        <atom name="TitAccessionNo">TR11285/2</atom>
        <atom name="TitObjectStatus">Loan Exhibition</atom>
        <atom name="SumCreditLine"></atom>
        <table name="RigRightsRef_tab">
          <tuple>
            <atom name="RigAcknowledgement">Public Domain</atom>
          </tuple>
        </table>
        <atom name="RefCatalogueRaisonne"></atom>
        <atom name="CreDateCreated">about 1900</atom>
        <atom name="CreDateDesigned"></atom>
        <table name="Creator1">
          <tuple>
            <atom name="CreRole">Artist</atom>
            <atom name="irn">614616</atom>
            <atom name="NamFullName">Edouard Vuillard</atom>
            <atom name="NamFirst">Edouard</atom>
            <atom name="NamMiddle"></atom>
            <atom name="NamLast">Vuillard</atom>
            <atom name="NamOrganisation"></atom>
            <atom name="ColCollaborationName"></atom>
            <atom name="UlaName">Vuillard, Edouard</atom>
            <atom name="UlaUlanIdNo">500014954</atom>
            <atom name="BioNationality">French</atom>
          </tuple>
        </table>
        <atom name="TitObjectType">Visual Works: Paintings</atom>
        <atom name="AdmPublishWebNoPassword">No</atom>
        <table name="Dagwood">
          <tuple>
            <atom name="EleTitle">Dagwood ID for TR11285/2</atom>
            <atom name="RefBibliographicNotes">41196</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <atom name="irn">76429</atom>
        <atom name="TitMainTitle">Noëlle et sa mère</atom>
        <atom name="TitAccessionNo">TR11382</atom>
        <atom name="TitObjectStatus">Returned</atom>
        <atom name="SumCreditLine">Private Collection</atom>
        <table name="RigRightsRef_tab">
          <tuple>
            <atom name="RigAcknowledgement">Public Domain</atom>
          </tuple>
        </table>
        <atom name="RefCatalogueRaisonne"></atom>
        <atom name="CreDateCreated">1896</atom>
        <atom name="CreDateDesigned"></atom>
        <table name="Creator1">
          <tuple>
            <atom name="CreRole">Artist</atom>
            <atom name="irn">757</atom>
            <atom name="NamFullName">Maurice Denis</atom>
            <atom name="NamFirst">Maurice</atom>
            <atom name="NamMiddle"></atom>
            <atom name="NamLast">Denis</atom>
            <atom name="NamOrganisation"></atom>
            <atom name="ColCollaborationName"></atom>
            <atom name="UlaName">Denis, Maurice</atom>
            <atom name="UlaUlanIdNo">500032673</atom>
            <atom name="BioNationality">French</atom>
          </tuple>
        </table>
        <atom name="TitObjectType">Visual Works: Paintings</atom>
        <atom name="AdmPublishWebNoPassword">No</atom>
        <table name="Dagwood">
          <tuple>
            <atom name="EleTitle">Dagwood ID for TR11382</atom>
            <atom name="RefBibliographicNotes">46340</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <atom name="irn">76430</atom>
        <atom name="TitMainTitle">Gabrielle Vallotton at the villa Beaulieu</atom>
        <atom name="TitAccessionNo">TR11383/1</atom>
        <atom name="TitObjectStatus">Disposed</atom>
        <atom name="SumCreditLine"></atom>
        <table name="RigRightsRef_tab">
          <tuple>
            <atom name="RigAcknowledgement">Public Domain</atom>
          </tuple>
        </table>
        <atom name="RefCatalogueRaisonne"></atom>
        <atom name="CreDateCreated">1901</atom>
        <atom name="CreDateDesigned"></atom>
        <table name="Creator1">
          <tuple>
            <atom name="CreRole">Artist</atom>
            <atom name="irn">616677</atom>
            <atom name="NamFullName">Félix E. Vallotton</atom>
            <atom name="NamFirst">Félix</atom>
            <atom name="NamMiddle">Edouard</atom>
            <atom name="NamLast">Vallotton</atom>
            <atom name="NamOrganisation"></atom>
            <atom name="ColCollaborationName"></atom>
            <atom name="UlaName">Vallotton, Félix Edouard</atom>
            <atom name="UlaUlanIdNo">500017056</atom>
            <atom name="BioNationality">Swiss</atom>
          </tuple>
        </table>
        <atom name="TitObjectType">Visual Works: Photographs</atom>
        <atom name="AdmPublishWebNoPassword">No</atom>
        <table name="Dagwood">
          <tuple>
            <atom name="EleTitle">Dagwood ID for TR11383/1</atom>
            <atom name="RefBibliographicNotes">46372</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <atom name="irn">76431</atom>
        <atom name="TitMainTitle">Beach at Etretat</atom>
        <atom name="TitAccessionNo">TR11383/2</atom>
        <atom name="TitObjectStatus">Disposed</atom>
        <atom name="SumCreditLine"></atom>
        <table name="RigRightsRef_tab">
          <tuple>
            <atom name="RigAcknowledgement">Public Domain</atom>
          </tuple>
        </table>
        <atom name="RefCatalogueRaisonne"></atom>
        <atom name="CreDateCreated">1899</atom>
        <atom name="CreDateDesigned"></atom>
        <table name="Creator1">
          <tuple>
            <atom name="CreRole">Artist</atom>
            <atom name="irn">616677</atom>
            <atom name="NamFullName">Félix E. Vallotton</atom>
            <atom name="NamFirst">Félix</atom>
            <atom name="NamMiddle">Edouard</atom>
            <atom name="NamLast">Vallotton</atom>
            <atom name="NamOrganisation"></atom>
            <atom name="ColCollaborationName"></atom>
            <atom name="UlaName">Vallotton, Félix Edouard</atom>
            <atom name="UlaUlanIdNo">500017056</atom>
            <atom name="BioNationality">Swiss</atom>
          </tuple>
        </table>
        <atom name="TitObjectType">Visual Works: Photographs</atom>
        <atom name="AdmPublishWebNoPassword">No</atom>
        <table name="Dagwood">
          <tuple>
            <atom name="EleTitle">Dagwood ID for TR11383/2</atom>
            <atom name="RefBibliographicNotes">46373</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <atom name="irn">76432</atom>
        <atom name="TitMainTitle">Beach at Etretat</atom>
        <atom name="TitAccessionNo">TR11383/3</atom>
        <atom name="TitObjectStatus">Disposed</atom>
        <atom name="SumCreditLine"></atom>
        <table name="RigRightsRef_tab">
          <tuple>
            <atom name="RigAcknowledgement">Public Domain</atom>
          </tuple>
        </table>
        <atom name="RefCatalogueRaisonne"></atom>
        <atom name="CreDateCreated">1899</atom>
        <atom name="CreDateDesigned"></atom>
        <table name="Creator1">
          <tuple>
            <atom name="CreRole">Artist</atom>
            <atom name="irn">616677</atom>
            <atom name="NamFullName">Félix E. Vallotton</atom>
            <atom name="NamFirst">Félix</atom>
            <atom name="NamMiddle">Edouard</atom>
            <atom name="NamLast">Vallotton</atom>
            <atom name="NamOrganisation"></atom>
            <atom name="ColCollaborationName"></atom>
            <atom name="UlaName">Vallotton, Félix Edouard</atom>
            <atom name="UlaUlanIdNo">500017056</atom>
            <atom name="BioNationality">Swiss</atom>
          </tuple>
        </table>
        <atom name="TitObjectType">Visual Works: Photographs</atom>
        <atom name="AdmPublishWebNoPassword">No</atom>
        <table name="Dagwood">
          <tuple>
            <atom name="EleTitle">Dagwood ID for TR11383/3</atom>
            <atom name="RefBibliographicNotes">46374</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <atom name="irn">76433</atom>
        <atom name="TitMainTitle">Alley in Marseille</atom>
        <atom name="TitAccessionNo">TR11383/4</atom>
        <atom name="TitObjectStatus">Disposed</atom>
        <atom name="SumCreditLine"></atom>
        <table name="RigRightsRef_tab">
          <tuple>
            <atom name="RigAcknowledgement">Public Domain</atom>
          </tuple>
        </table>
        <atom name="RefCatalogueRaisonne"></atom>
        <atom name="CreDateCreated">1901</atom>
        <atom name="CreDateDesigned"></atom>
        <table name="Creator1">
          <tuple>
            <atom name="CreRole">Artist</atom>