<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    integer         irn
    text short      TitAccessionNo
    text short      TitPreviousAccessionNo
    text short      TitObjectStatus
    date            TitAccessionDate
    text long       TitMainTitle
    text long       TitSeriesTitle
    text long       TitCollectionTitle
    table           AltTitles
      text long       TitAlternateTitles
    end
    text long       TitTitleNotes
    text short      TitObjectType
    table           ObjectTypes
      text short      PhyMediaCategory
    end
    text short      CreDateCreated
    date            CreEarliestDate
    date            CreLatestDate
    text short      CreCreationPeriod
    text long       CreCreationDynasty
    table           Creator1
      text short      CreRole
      text long       CreCreatorAfterFollower
      integer         irn
      text long       SummaryData
    end
    table           Creator2
      text long       CreCreatorAttribution
      text long       CreCreationCultureOrPeople
      text long       CreCreationNationality2
    end
    table           CreLocation
      text short      CreCountry
      text short      CreState
      text short      CreDistrict
      text short      CreCity
    end
    table           MarkType
      text short      CreMarkType
    end
    text long       CrePrimaryInscriptions
    text long       CreCreationNotes
    date            EdiPublisherDate
    table           Medium
      text long       PhyMedium
    end
    table           Support
      text short      PhySupport
    end
    text long       PhyMediumAndSupport
    text short      PhyStyle
    text short      PhyTechnique
    text short      EdiImpression
    text long       PhyDescription
    text long       PhyConvertedDims
    table           Dimensions
      text short      PhyType
      float           PhyHeight
      float           PhyWidth
      float           PhyDepth
      float           PhyDiameter
      text short      PhyUnitLength
      float           PhyWeight
      text short      PhyUnitWeight
      text short      PhyDimensionNotes
    end
    text long       SumCreditLine
    table           Rights
      text long       RigAcknowledgement
    end
    text long       CreProvenance
    text short      PhyCollectionArea
    text short      LocMovementType
    tuple           LocCurrentLocationRef
      text short      LocLevel1
      text short      LocLevel2
      text short      LocLevel3
    end
    tuple           AssParentObjectRef
      integer         irn
    end
    text short      AssIsParent
    table           Children
      integer         irn
      text long       TitMainTitle
      table           Grandchildren
        integer         irn
        text long       TitMainTitle
      end
    end
    table           Related
      text short      AssRelationship
      integer         irn
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 1 -->
  <tuple>
    <atom name="irn">64628</atom>
    <atom name="TitAccessionNo">2009.390.1-.16</atom>
    <atom name="TitPreviousAccessionNo">TR10819/2-17 | EX2009.1.29</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">2009-12-17</atom>
    <atom name="TitMainTitle">Broken Family tea set</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes">.1A-B) teapot .2A-B) sugar bowl .3) creamer .4) cup .5) cup .6) cup .7) cup .8) saucer .9) saucer .10) saucer .11) saucer .12) platter .13) plate .14) plate .15) plate .16) plate</atom>
    <atom name="TitObjectType">Containers</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">ceramics</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">metalwork</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">tableware</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">dishes</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">pottery</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">tea services</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">teapots</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">lids</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">creamers</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">sugar bowls</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">cups</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">saucers</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">platters</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">plates</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1999</atom>
    <atom name="CreEarliestDate">1999</atom>
    <atom name="CreLatestDate">1999</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Designer</atom>
        <atom name="irn">5679</atom>
        <atom name="SummaryData">Bey, Jurgen</atom>
      </tuple>
      <tuple>
        <atom name="CreRole">Manufacturer</atom>
        <atom name="irn">5679</atom>
        <atom name="SummaryData">Bey, Jurgen</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">silver plate</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">ceramic</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">silver plate over existing ceramics</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique">metalworking</atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription">.1A-B) teapot .2A-B) sugar bowl .3) creamer .4) cup .5) cup .6) cup .7) cup .8) saucer .9) saucer .10) saucer .11) saucer .12) platter .13) plate .14) plate .15) plate .16) plate</atom>
    <atom name="PhyConvertedDims">Largest: 7-7/8 × 8-3/4 × 4-3/4 in.</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">7.8750</atom>
        <atom name="PhyWidth">8.7500</atom>
        <atom name="PhyDepth">4.7500</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 20 × 22 × 12 (largest)</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Deaccessioned Decorative/Design Arts Fund</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">© Jurgen Bey</atom>
      </tuple>
    </table>
    <atom name="CreProvenance">(Studio Makkink &amp; Bey, Rotterdam, The Netherlands); purchased by the Indianapolis Museum of Art in 2009.</atom>
    <atom name="PhyCollectionArea">903.2-Design Arts</atom>
    <atom name="LocMovementType">Exhibition Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">see related parts</atom>
      <atom name="LocLevel3"></atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">Yes</atom>
    <table name="Children">
      <tuple>
        <atom name="irn">68180</atom>
        <atom name="TitMainTitle">Broken Family teapot</atom>
        <table name="Grandchildren">
          <tuple>
            <atom name="irn">68181</atom>
            <atom name="TitMainTitle">Broken Family teapot</atom>
          </tuple>
          <tuple>
            <atom name="irn">68182</atom>
            <atom name="TitMainTitle">lid for Broken Family teapot</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <atom name="irn">68183</atom>
        <atom name="TitMainTitle">Broken Family sugar bowl</atom>
        <table name="Grandchildren">
          <tuple>
            <atom name="irn">68184</atom>
            <atom name="TitMainTitle">Broken Family sugar bowl</atom>
          </tuple>
          <tuple>
            <atom name="irn">68185</atom>
            <atom name="TitMainTitle">lid for Broken Family sugar bowl</atom>
          </tuple>
        </table>
      </tuple>
      <tuple>
        <atom name="irn">68186</atom>
        <atom name="TitMainTitle">Broken Family creamer</atom>
      </tuple>
      <tuple>
        <atom name="irn">68187</atom>
        <atom name="TitMainTitle">Broken Family cup</atom>
      </tuple>
      <tuple>
        <atom name="irn">68188</atom>
        <atom name="TitMainTitle">Broken Family cup</atom>
      </tuple>
      <tuple>
        <atom name="irn">68189</atom>
        <atom name="TitMainTitle">Broken Family cup</atom>
      </tuple>
      <tuple>
        <atom name="irn">68190</atom>
        <atom name="TitMainTitle">Broken Family cup</atom>
      </tuple>
      <tuple>
        <atom name="irn">68191</atom>
        <atom name="TitMainTitle">Broken Family saucer</atom>
      </tuple>
      <tuple>
        <atom name="irn">68192</atom>
        <atom name="TitMainTitle">Broken Family saucer</atom>
      </tuple>
      <tuple>
        <atom name="irn">68193</atom>
        <atom name="TitMainTitle">Broken Family saucer</atom>
      </tuple>
      <tuple>
        <atom name="irn">68194</atom>
        <atom name="TitMainTitle">Broken Family saucer</atom>
      </tuple>
      <tuple>
        <atom name="irn">68195</atom>
        <atom name="TitMainTitle">Broken Family platter</atom>
      </tuple>
      <tuple>
        <atom name="irn">68196</atom>
        <atom name="TitMainTitle">Broken Family plate</atom>
      </tuple>
      <tuple>
        <atom name="irn">68197</atom>
        <atom name="TitMainTitle">Broken Family plate</atom>
      </tuple>
      <tuple>
        <atom name="irn">68198</atom>
        <atom name="TitMainTitle">Broken Family plate</atom>
      </tuple>
      <tuple>
        <atom name="irn">68199</atom>
        <atom name="TitMainTitle">Broken Family plate</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="irn">68180</atom>
    <atom name="TitAccessionNo">2009.390.1A-B</atom>
    <atom name="TitPreviousAccessionNo">TR10819/2A-B | EX2009.1.29</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">2009-12-17</atom>
    <atom name="TitMainTitle">Broken Family teapot</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Furnishings</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">ceramics</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">metalwork</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">tableware</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">dishes</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">pottery</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">teapots</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">lids</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1999</atom>
    <atom name="CreEarliestDate">1999</atom>
    <atom name="CreLatestDate">1999</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Designer</atom>
        <atom name="irn">5679</atom>
        <atom name="SummaryData">Bey, Jurgen</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">silver plate</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">ceramic</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">silver plate over existing ceramics</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique"></atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">7-1/2 x 5 x 3-1/2 in.</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">7.5000</atom>
        <atom name="PhyWidth">5.0000</atom>
        <atom name="PhyDepth">3.5000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 26 x 12.7 x 8.9</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Deaccessioned Decorative/Design Arts Fund</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">© Jurgen Bey</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">903.2-Design Arts</atom>
    <atom name="LocMovementType">Exhibition Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">see related parts</atom>
      <atom name="LocLevel3"></atom>
    </tuple>
    <tuple name="AssParentObjectRef">
      <atom name="irn">64628</atom>
    </tuple>
    <atom name="AssIsParent">Yes</atom>
    <table name="Children">
      <tuple>
        <atom name="irn">68181</atom>
        <atom name="TitMainTitle">Broken Family teapot</atom>
      </tuple>
      <tuple>
        <atom name="irn">68182</atom>
        <atom name="TitMainTitle">lid for Broken Family teapot</atom>
      </tuple>
    </table>
    <table name="Related">
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68183</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68186</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68187</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68188</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68189</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68190</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68191</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68192</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68193</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68194</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68195</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68196</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68197</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68198</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68199</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="irn">68181</atom>
    <atom name="TitAccessionNo">2009.390.1A</atom>
    <atom name="TitPreviousAccessionNo">TR10819/2A | EX2009.1.29</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">2009-12-17</atom>
    <atom name="TitMainTitle">Broken Family teapot</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Furnishings</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">ceramics</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">metalwork</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">tableware</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">dishes</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">pottery</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">tea services</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">teapots</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1999</atom>
    <atom name="CreEarliestDate">1999</atom>
    <atom name="CreLatestDate">1999</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Designer</atom>
        <atom name="irn">5679</atom>
        <atom name="SummaryData">Bey, Jurgen</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">silver plate</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">ceramic</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">silver plate over existing ceramics</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique"></atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">7-1/2 x 5 x 3-1/2 in.</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">7.5000</atom>
        <atom name="PhyWidth">5.0000</atom>
        <atom name="PhyDepth">3.5000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 26 x 12.7 x 8.9</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Deaccessioned Decorative/Design Arts Fund</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">© Jurgen Bey</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">903.2-Design Arts</atom>
    <atom name="LocMovementType">Exhibition Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">Contemporary Design Gallery</atom>
      <atom name="LocLevel3">H302</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
      <atom name="irn">68180</atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <table name="Related">
      <tuple>
        <atom name="AssRelationship">blanket record</atom>
        <atom name="irn">68180</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68182</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="irn">68182</atom>
    <atom name="TitAccessionNo">2009.390.1B</atom>
    <atom name="TitPreviousAccessionNo">TR10819/2B | EX2009.1.29</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">2009-12-17</atom>
    <atom name="TitMainTitle">lid for Broken Family teapot</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Furnishings</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">ceramics</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">metalwork</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">tableware</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">dishes</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">pottery</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">lids</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1999</atom>
    <atom name="CreEarliestDate">1999</atom>
    <atom name="CreLatestDate">1999</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Designer</atom>
        <atom name="irn">5679</atom>
        <atom name="SummaryData">Bey, Jurgen</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">silver plate</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">ceramic</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">silver plate over existing ceramics</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique"></atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">No measurement details.</atom>
    <atom name="SumCreditLine">Deaccessioned Decorative/Design Arts Fund</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">© Jurgen Bey</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">903.2-Design Arts</atom>
    <atom name="LocMovementType">Exhibition Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">Contemporary Design Gallery</atom>
      <atom name="LocLevel3">H302</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
      <atom name="irn">68180</atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <table name="Related">
      <tuple>
        <atom name="AssRelationship">blanket record</atom>
        <atom name="irn">68180</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68181</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="irn">68183</atom>
    <atom name="TitAccessionNo">2009.390.2A-B</atom>
    <atom name="TitPreviousAccessionNo">TR10819/3A-B | EX2009.1.29</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">2009-12-17</atom>
    <atom name="TitMainTitle">Broken Family sugar bowl</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Furnishings</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">ceramics</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">metalwork</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">tableware</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">dishes</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">pottery</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">sugar bowls</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">lids</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1999</atom>
    <atom name="CreEarliestDate">1999</atom>
    <atom name="CreLatestDate">1999</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Designer</atom>
        <atom name="irn">5679</atom>
        <atom name="SummaryData">Bey, Jurgen</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">silver plate</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">ceramic</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">silver plate over existing ceramics</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique"></atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">5-3/4 x 5 in.</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">5.7500</atom>
        <atom name="PhyDiameter">5.0000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 14.6 x 12.7</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Deaccessioned Decorative/Design Arts Fund</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">© Jurgen Bey</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">903.2-Design Arts</atom>
    <atom name="LocMovementType">Exhibition Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">see related parts</atom>
      <atom name="LocLevel3"></atom>
    </tuple>
    <tuple name="AssParentObjectRef">
      <atom name="irn">64628</atom>
    </tuple>
    <atom name="AssIsParent">Yes</atom>
    <table name="Children">
      <tuple>
        <atom name="irn">68184</atom>
        <atom name="TitMainTitle">Broken Family sugar bowl</atom>
      </tuple>
      <tuple>
        <atom name="irn">68185</atom>
        <atom name="TitMainTitle">lid for Broken Family sugar bowl</atom>
      </tuple>
    </table>
    <table name="Related">
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68180</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68186</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68187</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68188</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68189</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68190</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68191</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68192</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68193</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68194</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68195</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68196</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68197</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68198</atom>
      </tuple>
      <tuple>
        <atom name="AssRelationship">part</atom>
        <atom name="irn">68199</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="irn">68184</atom>
    <atom name="TitAccessionNo">2009.390.2A</atom>
    <atom name="TitPreviousAccessionNo">TR10819/3A | EX2009.1.29</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">2009-12-17</atom>
    <atom name="TitMainTitle">Broken Family sugar bowl</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Furnishings</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">ceramics</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">metalwork</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">tableware</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">dishes</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">pottery</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">sugar bowls</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1999</atom>
    <atom name="CreEarliestDate">1999</atom>
    <atom name="CreLatestDate">1999</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Designer</atom>
        <atom name="irn">5679</atom>
        <atom name="SummaryData">Bey, Jurgen</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">silver plate</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">ceramic</atom>
      </tuple>
    </table>